### ISSUE TITLE
When used with Sodium, a black box appears

### ISSUE THREAD

**Issue by Neubulae** [18107/Flex-FOV-fabric#3]
![image](https://user-images.githubusercontent.com/24774842/91306249-db867700-e7de-11ea-9768-76d9f364b076.png)
After switching to GL2.0 the problem resolves but I don't know why this happens, as other boxes function as normal.

**Comment by 18107** [comment]
Is this black box affected by the fov slider?

**Comment by Neubulae** [comment]
> Is this black box affected by the fov slider?

Yes indeed

**Comment by Neubulae** [comment]
For whatever reason, when I press F1, now there are two of them. Does that mean something?
![image](https://user-images.githubusercontent.com/24774842/91307020-ff968800-e7df-11ea-9d18-d8f876ec1b83.png)

**Comment by Neubulae** [comment]
I see, when I'm in spectator mode two boxes happens.

**Comment by 18107** [comment]
Can you please test this version and tell me if anything different happens?
https://www.dropbox.com/s/u2gtazwghxs1ias/FlexFOV-1.1.3.jar?dl=1

**Comment by Neubulae** [comment]
> Can you please test this version and tell me if anything different happens?
> https://www.dropbox.com/s/u2gtazwghxs1ias/FlexFOV-1.1.3.jar?dl=1

Sure, I'll go

**Comment by Neubulae** [comment]
Nothing changed, the box is still there.

**Comment by 18107** [comment]
I'm not sure what the problem is. I'll look into it tomorrow.

**Comment by Neubulae** [comment]
https://github.com/jellysquid3/sodium-fabric/pull/250
BTW, I should mention that I've been using this fork in order to let Sodium work on 1.16.2. Graphics is set to Fancy.

**Comment by Neubulae** [comment]
How's the problem?

**Comment by 18107** [comment]
I am unable to duplicate the issue. Can you please try Flex FOV 1.1.2 for Minecraft 1.16.1 with Sodium mc1.16.1-0.1.0?

https://www.curseforge.com/minecraft/mc-mods/flex-fov/files/3033005
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3026258
https://www.curseforge.com/minecraft/mc-mods/sodium/files/3003093

**Comment by Neubulae** [comment]
https://github.com/FlashyReese/sodium-fabric

after switching to this fork, the issue resolved. I suspect this is related to the driver problem since it merged a pacth for some AMD and Intel Drivers
