### ISSUE TITLE
Unable to find controls

### ISSUE THREAD

**Issue by Lord-Memester** [18107/Flex-FOV-fabric#5]
I can't find any options for controls or how to access the settings.

**Comment by 18107** [comment]
![FlexFOV Options](https://user-images.githubusercontent.com/7885724/99301639-5f15a880-28a2-11eb-8cc5-18426a1719f5.png)
This button has a hard-coded position. Sometimes another mod will add a button in the same location, and you will not be able to see it.

**Comment by Lord-Memester** [comment]
Thanks!
Also, what version of the fabric API does this require?

**Comment by 18107** [comment]
It should work with all versions of fabric-api for the relevant Minecraft version. I have confirmed that it works with fabric-api 0.25.1 build 416.
